# media_dirs.txt
# use one dir per line (full path)
# only [video] and [audio] sections
# are supported at this time.

[video]
/media/chris/xeon_movies1
/media/chris/xeon_movies2
/media/chris/xeon_movies3
/media/chris/video_460G
/media/chris/TV

[audio]
/Audio
/Audio2
/Audio3
/Audio4


