name: Build with GCC 16

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install GCC/G++ 16 PPA and run make
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y tcl jq make g++-16
          make config
          make
          make install
          make test
          make uninstall

